# Generated by Django 3.0.6 on 2020-06-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
