# Generated by Django 3.1.1 on 2020-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posts_description_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-publication_date',), 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='description_html',
        ),
    ]
