# Generated by Django 3.1.1 on 2020-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200914_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
